name: valider tp2

on:
  push:
    branches:
      - master
    tags:
      - v1
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'ciclad_v3/ciclad_v3_main.cpp'
      - 'ciclad_v3/ciclad_v3_impl.cpp'
      - 'ciclad_v3/ciclad_v3_impl.h'

jobs:
  job_1:
    name: job principale
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: affichage
      run: |
        echo $OSTYPE
        cat /proc/cpuinfo
        gcc -v
        g++ -v
    #- name: installation cuint
    #  run: |
    #    sudo apt-get install -y libcunit1 libcunit1-doc libcunit1-dev
    - name: compilation
      run: |
        cd ciclad_v3
        pwd
        g++ -O2 -std=c++14 -lopenmp -o ciclad_v3 ciclad_v3_impl.cpp ciclad_v3_main.cpp
    - name: testing
      run: |
        cd ciclad_v3
        ls -lahs ciclad_v3*
        #echo -e "0 01 0\n10 02 A1 0.100\n20 02 A2 0.11" > t1.txt
        #cat t1.txt | ./tp2
