name: ciclad v3
on:
  push:
    branches:
      - master
    tags:
      - v1
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'ciclad_v3/ciclad_v3_main.cpp'
      - 'ciclad_v3/ciclad_v3_impl.cpp'
      - 'ciclad_v3/ciclad_v3_impl.h'
      - 'ciclad_v3/gitaction.txt'

jobs:
  job_1:
    name: job principale
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: affichage
      run: |
        echo $OSTYPE
        cat /proc/cpuinfo
        cat /proc/meminfo
        gcc -v
        g++ -v
        mkfifo --help
    #- name: installation cuint
    #  run: |
    #    sudo apt-get install -y libcunit1 libcunit1-doc libcunit1-dev
    - name: compilation
      run: |
        cd ciclad_v3
        pwd
        g++ -O2 -std=c++14 -ffast-math -o ciclad_v3 ciclad_v3_impl.cpp ciclad_v3_main.cpp
        g++ -O2 -o streamer streamer.cpp
    - name: testing add-remove
      run: |
        cd ciclad_v3
        ls -lahs ciclad_v3*
        ./ciclad_v3 -v < ../datasets/test-a-r-10.txt
    - name: testing mushroom
      run: |
        cd ciclad_v3
        ./streamer 10000 ./f.txt file < ../datasets/mushroom.dat
        head -n 1 f.txt
        tail -n 1 f.txt
        ./ciclad_v3 -v < f.txt
    - name: testing synth2
      run: |
        cd ciclad_v3
        ./streamer 10000 ./f.txt file < ../datasets/testdb_gen2.txt
        head -n 1 f.txt
        tail -n 1 f.txt
        ./ciclad_v3 -v < f.txt
    - name: testing synth1
      run: |
        cd ciclad_v3
        ./streamer 100000 ./f.txt file < ../datasets/testdb_gen.txt
        head -n 1 f.txt
        tail -n 1 f.txt
        ./ciclad_v3 -v < f.txt
